# Generated by Django 3.2.9 on 2021-11-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211111_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='defualt.jpg', null=True, upload_to=''),
        ),
    ]
